#!/bin/sh
gem install actionmailer --no-rdoc --no-ri --version 2.2.2
gem install actionpack --no-rdoc --no-ri --version 2.2.2
gem install activerecord --no-rdoc --no-ri --version 2.2.2
gem install activeresource --no-rdoc --no-ri --version 2.2.2
gem install activesupport --no-rdoc --no-ri --version 2.3.2
gem install activesupport --no-rdoc --no-ri --version 2.2.2
gem install cgi_multipart_eof_fix --no-rdoc --no-ri --version 2.5.0
gem install composite_primary_keys --no-rdoc --no-ri --version 2.2.2
gem install daemons --no-rdoc --no-ri --version 1.0.10
gem install fastthread --no-rdoc --no-ri --version 1.0.7
gem install friendly_id --no-rdoc --no-ri --version 2.1.1
gem install gem_plugin --no-rdoc --no-ri --version 0.2.3
gem install haml --no-rdoc --no-ri --version 2.0.9
gem install httpclient --no-rdoc --no-ri --version 2.1.4
gem install json --no-rdoc --no-ri --version 1.2.0
gem install mime-types --no-rdoc --no-ri --version 1.16
gem install mongrel --no-rdoc --no-ri --version 1.1.5
gem install mongrel_cluster --no-rdoc --no-ri --version 1.0.5
gem install net-ssh --no-rdoc --no-ri --version 2.0.11
gem install paperclip --no-rdoc --no-ri --version 2.1.2
gem install rails --no-rdoc --no-ri --version 2.2.2
gem install rake --no-rdoc --no-ri --version 0.8.3
gem install rest-client --no-rdoc --no-ri --version 1.3.1
gem install rspec --no-rdoc --no-ri --version 1.2.6
gem install rubycrowd --no-rdoc --no-ri --version 0.0.10
gem install searchlogic --no-rdoc --no-ri --version 1.6.6
gem install soap4r --no-rdoc --no-ri --version 1.5.8
