#!/usr/bin/env ruby

if ARGV[0]
  RAILS_ENV = ARGV[0] 
else
  RAILS_ENV = "development"
end

require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'

Project.all.each do |project|
  
  if project.status == ProjectStatus.active
    puts "Deploying: #{project.name}"
    project.deploy_nodelay
  end
  
end